### ISSUE TITLE
Help Autoremove-torrents

### ISSUE THREAD

**Issue by Morcegolas** [HalfCoke/HalfCoke.github.io#69]
Hello, I'm trying to reach you regarding autoremove-torrents docker container, but can't open an issue there. 
How can I reach you regarding this?
I need your help, I manage to install the container with your image but I'm getting one error and it only works if I run the command manually, the cronjob is not working. 
As I'm using with qbittorrent, and I was also getting another error, I had to extract one egg file and create a directory with the same name to get the error fixed, but the auto run won't work, even when I start the docker, because if it works at least this way I would set a container restart every hour to delete the torrents, but even this way I can't get it going. 
Hope you can help me out. 
Thanks.

**Comment by HalfCoke** [comment]
the docker log may be not correct, but you can see '/var/log' in container.


my docker compose file:
```yaml
version: '3.9'
services:
    autoremove-torrents:
        restart: always
        volumes:
            - '/volume1/Data/autoremove-torrents/pt.yml:/etc/autoremove_torrents/config.yml'
        container_name: autoremove-torrents
        image: halfcoke/autoremove-torrents
```

my config file: 
```yaml

nas: # 任务名称
  # 第二部分：登录信息
  client: qbittorrent
  host: http://192.168.XXX.XXX:8085
  username: XXX
  password: 'XXXX'
  # 第三部分：策略块（删除种子的条件）
  strategies:
    ubits:
      categories: 
        - ubits 
      seeding_time: 288000
      seed_size:
        limit: 3000
        action: remove-old-seeds
    mteam:
      categories: 
        - mteam 
      seeding_time: 432000
      seed_size:
        limit: 3000
        action: remove-old-seeds
    carpt:
      categories: 
        - carpt 
      seeding_time: 432000
      seed_size:
        limit: 3000
        action: remove-old-seeds
  # 是否同时删除本地数据，默认为否
  delete_data: true
```

<img width="660" alt="image" src="https://github.com/HalfCoke/HalfCoke.github.io/assets/42169012/64a255da-ea8b-42af-9cfa-fe2414b0d1f5">
